deployment:
  name: nginx
  replicas: 2
  repository:
  port: 8080
    image: gcr.io/google-samples/hello-app
    tag: 1.0.0

service:
  name: my-service
  port: 80
  type: NodePort

ingress:
  name: ing
  path: /test
